### ISSUE TITLE
Running with outputMatch flag dies even with node 6+

### ISSUE THREAD

**Issue by zerodevx** [mathiasrw/rexreplace#24]
Hi @mathiasrw, thanks for developing this. I use this a lot for npm run scripts. An issue I'm facing is running with `--output-match` flag errors with a `outputMatch is only supported in node 6+`, but I'm on node v10.15.2?

**Comment by mathiasrw** [comment]
This is terrible!

Thank you for letting me know. Ill look into it!

**Comment by danielcrabtree** [comment]
Same problem with ```--replacement-js```. With Node 10 it causes 
> Error: Captured groups for javascript replacement is only supported in node 6+

The bug appears to be caused by the version comparisons using string comparisons, e.g. process.versions.node < '6'.

**Comment by mathiasrw** [comment]
Note to self:

    const NODE_MAJOR_VERSION = process.versions.node.split('.')[0];
    if (NODE_MAJOR_VERSION < 12) {
      throw new Error('Requires Node 12 (or higher)');
    }

**Comment by mathiasrw** [comment]
Sorry for being so long. Side projects some times needs to lay for a bit. 

@danielcrabtree Can you please verify that this is working OK for you now with the latest version of rexreplace?

**Comment by danielcrabtree** [comment]
@mathiasrw Yes, it's working now. Thanks for fixing this.

Side question: Is there any difference between --replacement-js and --replacement-js-dynamic in older versions? I couldn't find any notes on this change.

**Comment by mathiasrw** [comment]
--replacement-js-dynamic was the old way of saying that you want to recalculate the replacement for each match where --replacement-js would only calculate them once (per file)

I think it was from version 3 to 4 that --replacement-js-dynamic got deprecated because I made a check on capturing groups - that would normally be the case with wanting to recalculate for each match. Another use case would be to have a very specific timestamp for each match. This can be done by adding a capturing group of the full string.
